### ISSUE TITLE
Minimal viable product | Iteration 1

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/brc-analytics#107]
# Key specs for the MVP1 

- [x] Have as many species as possible listed in https://brc-analytics.org/data/organisms
- [ ] Have all species from above registered as Galaxy Reference data with corresponding indices for `bowtie` (1 & 2), `bwa-mem` (1 & 2), `STAR`, `hisat2`, `SNPeff`
- [ ] Have accounts implemented linking brc-analytics with Galaxy (https://github.com/galaxyproject/brc-analytics/issues/77): **change** add Google authentication to .org only for MVP1
- [ ] Cross-linked for gene pages between NCBI and UCSC:

This UCSC page:

![image](https://github.com/user-attachments/assets/493baa6a-28ad-452e-8c8a-3b9c6e4d92ce)

should link to a corresponding gene page at NCBI Datasets via `Gene ID`:

![image](https://github.com/user-attachments/assets/e514051d-f075-49e6-a0b4-f7828cbf8cf1)

and vice versa

- [ ] Make sure datasets can be displayed from Galaxy in a corresponding UCSC Genome Browser (https://github.com/galaxyproject/galaxy/issues/18901)
- [ ] "Analyze" page for an organism (e.g., https://brc-analytics.org/data/organisms/GCA_000150785_1) should contain "Data portals" and "Analysis portals" sections as described here https://github.com/galaxyproject/brc-analytics/issues/106
- [ ] When one goes to Galaxy from "Data portals" section of the analysis page for a given species, the Galaxy should be focused on that species (https://github.com/galaxyproject/galaxy/issues/18882)

**Comment by nekrut** [comment]
# A more detailed description of BRC Analytics / Galaxy connection for MVP1

1. Start on Organism page
2. Click "Analyze" button
3. This takes you to analysis page (e.g., https://brc-analytics.org/data/organisms/GCA_000826245_1)
4. On analysis page you:
    - choose which instanced (test or main at this time)
    - choose a workflow (workflow needs to be from IWC to have a TRS ID)
    - click "Analyze"
5. If you selected "test" -> you get workflows start interface pre-set to `GCA_000826245_1`
6. If you selected "main" -> you just get  workflows start interface and set `dbKey` manually (https://github.com/galaxyproject/brc-analytics/issues/121)

**Comment by NoopDog** [comment]
Complete
